### ISSUE TITLE
Table name is not used as-is, database schema is forced to public

### ISSUE THREAD

**Issue by Exagone313** [PostHog/postgres-plugin#10]
When specifying a table name such as `posthog.events` (table `events` in schema `posthog`), it creates the table `public.posthogevents`.

Looking at the source code, it removes all non-alphanumeric or underscore characters and forces the usage of `public` schema.

## Actual result

Table name is badly escaped and you can't use another schema than `public`

## Expected result

Table name is escaped correctly and `public` schema is only used as a fallback when a schema isn't specified.

## Relevant source code

https://github.com/PostHog/postgres-plugin/blob/38a2c6e5b71e7009ef5ddf12a88af24fdb60151e/index.ts#L84-L87

https://github.com/PostHog/postgres-plugin/blob/38a2c6e5b71e7009ef5ddf12a88af24fdb60151e/index.ts#L267-L269

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [Postgres destination for batch exports](https://posthog.com/docs/cdp/batch-exports/postgres). The new system does support passing a `schema` field in the configuration.
