### ISSUE TITLE
Plugin disabled due to "TOO_MANY_SIMULTANEOUS_QUERIES"

### ISSUE THREAD

**Issue by KamilZet** [PostHog/postgres-plugin#4]
Today I received the following notification:

![image](https://user-images.githubusercontent.com/7767038/178696366-9936c6c9-a75c-4021-897d-35c3b719cd76.png)

This integration is running in our project since 2022 05 24 and it's the first time we are getting this error.

On the hourly granularity level we are getting the following volumes of events, to it's not so much actually.

![image](https://user-images.githubusercontent.com/7767038/178697010-84d0b71e-287d-4173-8703-fc7f1b06530c.png)

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [Postgres destination for batch exports](https://posthog.com/docs/cdp/batch-exports/postgres). The new export system is using less connections and writing bigger inserts, which should avoid this issue.
