### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by shalseban** [PostHog/postgres-plugin#5]
I am trying to connect to a postgres instance hosted on [Fly.io](https://fly.io/) but it fails with 

```Error: The server does not support SSL connections```

When I created a custom domain with certificates added to it and connect to 443 it fails with 

```Server closed the connection unexpectedly```

Not sure what I am missing here - is it not possible to connect to a postgres instance without SSL support? FWIW - I am able to connect on 443 from my local machine without any trouble.

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [Postgres destination for batch exports](https://posthog.com/docs/cdp/batch-exports/postgres).

The new system also requires TLS on the destination database, to reduce the risk of a data breach on the outgoing data flow.
